port = 4000
debug = false
db_dsn = "root:root@tcp(localhost:3306)/test?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"
jwt_secret = "test-jwt-secret"
jwt_expire_hour = 24

[redis]
addr = "127.0.0.1:6379"
password = ""