// Code generated by ent, DO NOT EDIT.

package ent

import (
	"frame/ent/adminuser"
	"frame/ent/schema"
	"frame/ent/user"
	"frame/ent/useractivity"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminuserMixin := schema.AdminUser{}.Mixin()
	adminuserMixinFields0 := adminuserMixin[0].Fields()
	_ = adminuserMixinFields0
	adminuserFields := schema.AdminUser{}.Fields()
	_ = adminuserFields
	// adminuserDescCreateTime is the schema descriptor for create_time field.
	adminuserDescCreateTime := adminuserMixinFields0[0].Descriptor()
	// adminuser.DefaultCreateTime holds the default value on creation for the create_time field.
	adminuser.DefaultCreateTime = adminuserDescCreateTime.Default.(func() time.Time)
	// adminuserDescUpdateTime is the schema descriptor for update_time field.
	adminuserDescUpdateTime := adminuserMixinFields0[1].Descriptor()
	// adminuser.DefaultUpdateTime holds the default value on creation for the update_time field.
	adminuser.DefaultUpdateTime = adminuserDescUpdateTime.Default.(func() time.Time)
	// adminuser.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	adminuser.UpdateDefaultUpdateTime = adminuserDescUpdateTime.UpdateDefault.(func() time.Time)
	// adminuserDescWalletAddress is the schema descriptor for wallet_address field.
	adminuserDescWalletAddress := adminuserFields[0].Descriptor()
	// adminuser.WalletAddressValidator is a validator for the "wallet_address" field. It is called by the builders before save.
	adminuser.WalletAddressValidator = adminuserDescWalletAddress.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescWalletAddress is the schema descriptor for wallet_address field.
	userDescWalletAddress := userFields[0].Descriptor()
	// user.WalletAddressValidator is a validator for the "wallet_address" field. It is called by the builders before save.
	user.WalletAddressValidator = userDescWalletAddress.Validators[0].(func(string) error)
	useractivityMixin := schema.UserActivity{}.Mixin()
	useractivityMixinFields0 := useractivityMixin[0].Fields()
	_ = useractivityMixinFields0
	useractivityFields := schema.UserActivity{}.Fields()
	_ = useractivityFields
	// useractivityDescCreateTime is the schema descriptor for create_time field.
	useractivityDescCreateTime := useractivityMixinFields0[0].Descriptor()
	// useractivity.DefaultCreateTime holds the default value on creation for the create_time field.
	useractivity.DefaultCreateTime = useractivityDescCreateTime.Default.(func() time.Time)
	// useractivityDescUpdateTime is the schema descriptor for update_time field.
	useractivityDescUpdateTime := useractivityMixinFields0[1].Descriptor()
	// useractivity.DefaultUpdateTime holds the default value on creation for the update_time field.
	useractivity.DefaultUpdateTime = useractivityDescUpdateTime.Default.(func() time.Time)
	// useractivity.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	useractivity.UpdateDefaultUpdateTime = useractivityDescUpdateTime.UpdateDefault.(func() time.Time)
}
