// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminUser is the predicate function for adminuser builders.
type AdminUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserActivity is the predicate function for useractivity builders.
type UserActivity func(*sql.Selector)
